#!/bin/bash

# get bootstrap and react dependencies
wget http://fb.me/react-0.9.0.min.js -P /opt/lc/resources/public/static/react/
wget https://github.com/twbs/bootstrap/releases/download/v3.1.1/bootstrap-3.1.1-dist.zip -P /opt/lc/resources/public/static/bootstrap/
wget http://code.jquery.com/jquery-1.11.0.min.js -P /opt/lc/resources/public/static/jquery

# unpack and remove archives
cd /opt/lc/resources/public/static/bootstrap; unzip bootstrap-*.zip; rm -f bootstrap-*.zip;
